1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

2. Print the NUMPY version and the configuration.


In [2]:
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

In [3]:
np.__version__

'1.22.4'


3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
a = np.random.random((2,3,5))

4. Print a.





In [5]:
a

array([[[0.96796799, 0.74197195, 0.65121879, 0.83534034, 0.40441298],
        [0.22244636, 0.95396931, 0.10023496, 0.58372989, 0.87365276],
        [0.72059532, 0.81355187, 0.41787419, 0.45376086, 0.89152413]],

       [[0.49906021, 0.2203296 , 0.28741006, 0.38444851, 0.01572305],
        [0.47991763, 0.10588561, 0.77613417, 0.60344777, 0.82695176],
        [0.40823092, 0.58380648, 0.37080771, 0.40378159, 0.15496559]]])


5. Create a 5x2x3 3-dimensional array with all values equaling 1.
Assign the array to variable "b"


In [6]:
b = np.ones((5,2,3))

6. Print b.

In [7]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

7. Do a and b have the same size? How do you prove that in Python code?

In [8]:
a.size

30

In [9]:
b.size

30

8. Are you able to add a and b? Why or why not?

In [10]:
np.array(a) + np.array(b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [11]:
c=b.reshape((2,3,5))

In [12]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [13]:
c.shape

(2, 3, 5)

10.  Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [14]:
d= a+c

In [15]:
d

array([[[1.96796799, 1.74197195, 1.65121879, 1.83534034, 1.40441298],
        [1.22244636, 1.95396931, 1.10023496, 1.58372989, 1.87365276],
        [1.72059532, 1.81355187, 1.41787419, 1.45376086, 1.89152413]],

       [[1.49906021, 1.2203296 , 1.28741006, 1.38444851, 1.01572305],
        [1.47991763, 1.10588561, 1.77613417, 1.60344777, 1.82695176],
        [1.40823092, 1.58380648, 1.37080771, 1.40378159, 1.15496559]]])

The sum of matrix is only possible when they have the same dimensions (2,3,5)

---------------------------------------------------------------------------

11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [16]:
a

array([[[0.96796799, 0.74197195, 0.65121879, 0.83534034, 0.40441298],
        [0.22244636, 0.95396931, 0.10023496, 0.58372989, 0.87365276],
        [0.72059532, 0.81355187, 0.41787419, 0.45376086, 0.89152413]],

       [[0.49906021, 0.2203296 , 0.28741006, 0.38444851, 0.01572305],
        [0.47991763, 0.10588561, 0.77613417, 0.60344777, 0.82695176],
        [0.40823092, 0.58380648, 0.37080771, 0.40378159, 0.15496559]]])

In [17]:
d

array([[[1.96796799, 1.74197195, 1.65121879, 1.83534034, 1.40441298],
        [1.22244636, 1.95396931, 1.10023496, 1.58372989, 1.87365276],
        [1.72059532, 1.81355187, 1.41787419, 1.45376086, 1.89152413]],

       [[1.49906021, 1.2203296 , 1.28741006, 1.38444851, 1.01572305],
        [1.47991763, 1.10588561, 1.77613417, 1.60344777, 1.82695176],
        [1.40823092, 1.58380648, 1.37080771, 1.40378159, 1.15496559]]])

The matrix d is the result of the sum of a and the ones matrix, so every value is 

d = 1 + a

12. Multiply a and c. Assign the result to e.

In [18]:
e = a*c

In [19]:
e

array([[[0.96796799, 0.74197195, 0.65121879, 0.83534034, 0.40441298],
        [0.22244636, 0.95396931, 0.10023496, 0.58372989, 0.87365276],
        [0.72059532, 0.81355187, 0.41787419, 0.45376086, 0.89152413]],

       [[0.49906021, 0.2203296 , 0.28741006, 0.38444851, 0.01572305],
        [0.47991763, 0.10588561, 0.77613417, 0.60344777, 0.82695176],
        [0.40823092, 0.58380648, 0.37080771, 0.40378159, 0.15496559]]])

13. Does e equal to a? Why or why not?

In [20]:
e==a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

a and e are iqual in values. e is the multiplication of a and the ones matrix

-------------------------------------------------------------------------

14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [21]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [22]:
print(d_max)
print(d_min)
print(d_mean)

1.967967992818517
1.015723054742954
1.525105079334766


15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [23]:
f = np.empty(shape=[2,3,5])

In [24]:
print(f)

[[[0.96796799 0.74197195 0.65121879 0.83534034 0.40441298]
  [0.22244636 0.95396931 0.10023496 0.58372989 0.87365276]
  [0.72059532 0.81355187 0.41787419 0.45376086 0.89152413]]

 [[0.49906021 0.2203296  0.28741006 0.38444851 0.01572305]
  [0.47991763 0.10588561 0.77613417 0.60344777 0.82695176]
  [0.40823092 0.58380648 0.37080771 0.40378159 0.15496559]]]


16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

If a value equals to d_mean, assign 50 to the corresponding value in f.

Assign 0 to the corresponding value(s) in f for d_min in d.

Assign 100 to the corresponding value(s) in f for d_max in d.

In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.


In [25]:
for fila in f:
    for valor in fila:
        for v in valor:
            if d_mean < v < d_max:
                v = 75
            elif d_min < v < d_mean:
                v = 25
            elif v==d_mean:
                v = 50
            elif v==d_min:
                v = 0
            elif v==d_max:
                v=100              

In [26]:
f

array([[[0.96796799, 0.74197195, 0.65121879, 0.83534034, 0.40441298],
        [0.22244636, 0.95396931, 0.10023496, 0.58372989, 0.87365276],
        [0.72059532, 0.81355187, 0.41787419, 0.45376086, 0.89152413]],

       [[0.49906021, 0.2203296 , 0.28741006, 0.38444851, 0.01572305],
        [0.47991763, 0.10588561, 0.77613417, 0.60344777, 0.82695176],
        [0.40823092, 0.58380648, 0.37080771, 0.40378159, 0.15496559]]])

17. Print d and f. Do you have your expected f?
For instance, if your d is:
```
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
```

Your f should be:
```
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

```

In [27]:
d

array([[[1.96796799, 1.74197195, 1.65121879, 1.83534034, 1.40441298],
        [1.22244636, 1.95396931, 1.10023496, 1.58372989, 1.87365276],
        [1.72059532, 1.81355187, 1.41787419, 1.45376086, 1.89152413]],

       [[1.49906021, 1.2203296 , 1.28741006, 1.38444851, 1.01572305],
        [1.47991763, 1.10588561, 1.77613417, 1.60344777, 1.82695176],
        [1.40823092, 1.58380648, 1.37080771, 1.40378159, 1.15496559]]])

In [28]:
f

array([[[0.96796799, 0.74197195, 0.65121879, 0.83534034, 0.40441298],
        [0.22244636, 0.95396931, 0.10023496, 0.58372989, 0.87365276],
        [0.72059532, 0.81355187, 0.41787419, 0.45376086, 0.89152413]],

       [[0.49906021, 0.2203296 , 0.28741006, 0.38444851, 0.01572305],
        [0.47991763, 0.10588561, 0.77613417, 0.60344777, 0.82695176],
        [0.40823092, 0.58380648, 0.37080771, 0.40378159, 0.15496559]]])

## Bonus
18.instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
```
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],


       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
```
Again, you don't need Numpy in this question.

In [29]:
for fila in f:
    for valor in fila:
        for v in valor:
            if d_mean < v < d_max:
                v = 'A'
            elif d_min < v < d_mean:
                v = 'B'
            elif v==d_mean:
                v = 'C'
            elif v==d_min:
                v = 'D'
            elif v==d_max:
                v= 'E'      

array([[[0.96796799, 0.74197195, 0.65121879, 0.83534034, 0.40441298],
        [0.22244636, 0.95396931, 0.10023496, 0.58372989, 0.87365276],
        [0.72059532, 0.81355187, 0.41787419, 0.45376086, 0.89152413]],

       [[0.49906021, 0.2203296 , 0.28741006, 0.38444851, 0.01572305],
        [0.47991763, 0.10588561, 0.77613417, 0.60344777, 0.82695176],
        [0.40823092, 0.58380648, 0.37080771, 0.40378159, 0.15496559]]])