In [3]:
%pip install numpy

  Using cached numpy-1.22.4-cp38-cp38-win_amd64.whl (14.8 MB)



In [16]:
import numpy as np


Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [17]:
a=np.random.random((2,3,5))

In [18]:
a

array([[[0.56457785, 0.06990637, 0.87150337, 0.9434349 , 0.35545132],
        [0.04944452, 0.88417304, 0.87780775, 0.60052069, 0.60098523],
        [0.78499745, 0.05228076, 0.81801644, 0.5448285 , 0.36790447]],

       [[0.85729512, 0.80656854, 0.70111156, 0.70768835, 0.34415386],
        [0.23266503, 0.95932474, 0.53515802, 0.57938362, 0.84888567],
        [0.81534694, 0.41481865, 0.70052343, 0.75097424, 0.83843737]]])

5. Create a 5x2x3 3-dimensional array with all values equaling 1.
Assign the array to variable "b"
6. Print b.

7. Do a and b have the same size? How do you prove that in Python code?

8. Are you able to add a and b? Why or why not?

In [19]:
b=np.ones((5,2,3))


In [20]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [21]:
print(a == b)

False


C:\Users\javip\AppData\Local\Temp\ipykernel_2204\1776171489.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(a == b)


In [22]:
False, no tienen el mismo tamaño

SyntaxError: invalid syntax (2017955093.py, line 1)

9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".



10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?



11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [23]:
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [89]:
d = a + c
d

array([[[1.56457785, 1.06990637, 1.87150337, 1.9434349 , 1.35545132],
        [1.04944452, 1.88417304, 1.87780775, 1.60052069, 1.60098523],
        [1.78499745, 1.05228076, 1.81801644, 1.5448285 , 1.36790447]],

       [[1.85729512, 1.80656854, 1.70111156, 1.70768835, 1.34415386],
        [1.23266503, 1.95932474, 1.53515802, 1.57938362, 1.84888567],
        [1.81534694, 1.41481865, 1.70052343, 1.75097424, 1.83843737]]])

In [88]:
a

array([[[0.56457785, 0.06990637, 0.87150337, 0.9434349 , 0.35545132],
        [0.04944452, 0.88417304, 0.87780775, 0.60052069, 0.60098523],
        [0.78499745, 0.05228076, 0.81801644, 0.5448285 , 0.36790447]],

       [[0.85729512, 0.80656854, 0.70111156, 0.70768835, 0.34415386],
        [0.23266503, 0.95932474, 0.53515802, 0.57938362, 0.84888567],
        [0.81534694, 0.41481865, 0.70052343, 0.75097424, 0.83843737]]])

In [90]:
d

array([[[1.56457785, 1.06990637, 1.87150337, 1.9434349 , 1.35545132],
        [1.04944452, 1.88417304, 1.87780775, 1.60052069, 1.60098523],
        [1.78499745, 1.05228076, 1.81801644, 1.5448285 , 1.36790447]],

       [[1.85729512, 1.80656854, 1.70111156, 1.70768835, 1.34415386],
        [1.23266503, 1.95932474, 1.53515802, 1.57938362, 1.84888567],
        [1.81534694, 1.41481865, 1.70052343, 1.75097424, 1.83843737]]])

In [87]:
Ahora se han sumado porque tienen las mismas dimensiones, y se suman por por punto de fila y columna , no por total.

SyntaxError: invalid syntax (4099790107.py, line 1)


12. Multiply a and c. Assign the result to e.



13. Does e equal to a? Why or why not?




14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"




15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [29]:
e = a*c
e == a
#Si, tiene el mismo valor porque todos los valores de c tienen el valor 1.


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [93]:
d_max=d.max()
d_max

1.9593247415833708

In [94]:
d_min=d.min()
d_min

1.0494445175246252

In [95]:
d_mean=d.mean()
d_mean

1.6159389260069796

In [96]:
f=np.empty((2,3,5))
print(f)


[[[1.56457785 1.06990637 1.87150337 1.9434349  1.35545132]
  [1.04944452 1.88417304 1.87780775 1.60052069 1.60098523]
  [1.78499745 1.05228076 1.81801644 1.5448285  1.36790447]]

 [[1.85729512 1.80656854 1.70111156 1.70768835 1.34415386]
  [1.23266503 1.95932474 1.53515802 1.57938362 1.84888567]
  [1.81534694 1.41481865 1.70052343 1.75097424 1.83843737]]]


In [ ]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [119]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] ==d.max():
                f[i][j][k]= 100
            elif d[i][j][k] < d.max() and d[i][j][k] >d.mean() :
                f[i][j][k]= 75
            elif d[i][j][k] == d.mean():
                f[i][j][k]= 50
            elif d[i][j][k] < d.mean() and d[i][j][k]> d.min():
                f[i][j][k]= 25
            elif d[i][j][k] == d.min():
                f[i][j][k]=0
              
            

In [120]:
f

array([[[ 25.,  25., 100.,  25.,  25.],
        [  0.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  25.]],

       [[ 75.,  75.,  75.,  75.,  75.],
        [ 75.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  25.]]])

In [ ]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [128]:
g=f.astype(str)


In [130]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] ==d.max():
                g[i][j][k]= 'A'
            elif d[i][j][k] < d.max() and d[i][j][k] >d.mean() :
                g[i][j][k]= 'B'
            elif d[i][j][k] == d.mean():
                g[i][j][k]= 'C'
            elif d[i][j][k] < d.mean() and d[i][j][k]> d.min():
                g[i][j][k]= 'D'
            elif d[i][j][k] == d.min():
                g[i][j][k]= 'F'

In [131]:
g

array([[['D', 'D', 'A', 'D', 'D'],
        ['F', 'D', 'D', 'D', 'D'],
        ['D', 'D', 'D', 'D', 'D']],

       [['B', 'B', 'B', 'B', 'B'],
        ['B', 'D', 'D', 'D', 'D'],
        ['D', 'D', 'D', 'D', 'D']]], dtype='<U32')