In [1]:
#1. Import the NUMPY package under the name np.
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [2]:
#2. Print the NUMPY version and the configuration.


print(np.__version__)
print(np.show_config())


1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alexd/Downloads/DescargaAnaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alexd/Downloads/DescargaAnaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alexd/Downloads/DescargaAnaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alexd/Downloads/DescargaAnaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alexd/Downloads/DescargaAnaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/alexd/Downloads/DescargaAnaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/alexd/Downloads/DescargaAnaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS',

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


a=np.random.random((2,3,5))


In [4]:
#4. Print a.

a



array([[[0.98349318, 0.39081549, 0.39495457, 0.66354012, 0.35549264],
        [0.3431953 , 0.8985985 , 0.98009795, 0.73363821, 0.46582344],
        [0.79059955, 0.08881731, 0.95633833, 0.99059743, 0.38536392]],

       [[0.81124126, 0.77190976, 0.64098742, 0.85584239, 0.59998085],
        [0.63480094, 0.21124504, 0.70146329, 0.18897125, 0.95623167],
        [0.67646795, 0.15407412, 0.98190996, 0.55392822, 0.53395564]]])

In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"


b=np.ones([5,2,3])


In [6]:
#6. Print b.


b


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
#7. Do a and b have the same size? How do you prove that in Python code?

# Respuesta: a y b no tienen la misma medida. Lo demostramos con la dimensión:
print(a.shape)
print(b.shape)



(2, 3, 5)
(5, 2, 3)


In [8]:
#8. Are you able to add a and b? Why or why not?


# Respuesta: no es posible porque no tienen las mismas dimensiones. Lo demuestro:
c=a+b
c


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [12]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c=b.reshape(2,3,5)
print(c)
print(c.shape)



[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


In [13]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d=a+c
print(d)



[[[1.98349318 1.39081549 1.39495457 1.66354012 1.35549264]
  [1.3431953  1.8985985  1.98009795 1.73363821 1.46582344]
  [1.79059955 1.08881731 1.95633833 1.99059743 1.38536392]]

 [[1.81124126 1.77190976 1.64098742 1.85584239 1.59998085]
  [1.63480094 1.21124504 1.70146329 1.18897125 1.95623167]
  [1.67646795 1.15407412 1.98190996 1.55392822 1.53395564]]]


In [14]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


print(a)
print(d)
print(d.shape)



[[[0.98349318 0.39081549 0.39495457 0.66354012 0.35549264]
  [0.3431953  0.8985985  0.98009795 0.73363821 0.46582344]
  [0.79059955 0.08881731 0.95633833 0.99059743 0.38536392]]

 [[0.81124126 0.77190976 0.64098742 0.85584239 0.59998085]
  [0.63480094 0.21124504 0.70146329 0.18897125 0.95623167]
  [0.67646795 0.15407412 0.98190996 0.55392822 0.53395564]]]
[[[1.98349318 1.39081549 1.39495457 1.66354012 1.35549264]
  [1.3431953  1.8985985  1.98009795 1.73363821 1.46582344]
  [1.79059955 1.08881731 1.95633833 1.99059743 1.38536392]]

 [[1.81124126 1.77190976 1.64098742 1.85584239 1.59998085]
  [1.63480094 1.21124504 1.70146329 1.18897125 1.95623167]
  [1.67646795 1.15407412 1.98190996 1.55392822 1.53395564]]]
(2, 3, 5)


In [15]:
#12. Multiply a and c. Assign the result to e.

e=a*c
e


array([[[0.98349318, 0.39081549, 0.39495457, 0.66354012, 0.35549264],
        [0.3431953 , 0.8985985 , 0.98009795, 0.73363821, 0.46582344],
        [0.79059955, 0.08881731, 0.95633833, 0.99059743, 0.38536392]],

       [[0.81124126, 0.77190976, 0.64098742, 0.85584239, 0.59998085],
        [0.63480094, 0.21124504, 0.70146329, 0.18897125, 0.95623167],
        [0.67646795, 0.15407412, 0.98190996, 0.55392822, 0.53395564]]])

In [16]:
#13. Does e equal to a? Why or why not?


print((a == e ).all())

#Porque multiplicas la matriz a por la matriz c y la matriz c es todo =1



True


In [17]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


d_max=d.max()
d_min=d.min()
d_mean=d.mean()

print(d_max)
print(d_min)
print(d_mean)



1.9905974344090958
1.0888173097753184
1.6231458564794656


In [18]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


f=np.empty((2,3,5))
f



array([[[0.98349318, 0.39081549, 0.39495457, 0.66354012, 0.35549264],
        [0.3431953 , 0.8985985 , 0.98009795, 0.73363821, 0.46582344],
        [0.79059955, 0.08881731, 0.95633833, 0.99059743, 0.38536392]],

       [[0.81124126, 0.77190976, 0.64098742, 0.85584239, 0.59998085],
        [0.63480094, 0.21124504, 0.70146329, 0.18897125, 0.95623167],
        [0.67646795, 0.15407412, 0.98190996, 0.55392822, 0.53395564]]])

In [19]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

for array in range(d.shape[0]):
    for subfila in range(d.shape[1]):
        for e in range(d.shape[2]):
            if d[array][subfila][e]> d_min and d[array][subfila][e]< d_mean:
                f[array][subfila][e] =25
            elif d[array][subfila][e]>d_mean and d[array][subfila][e]<d_max:
                f[array][subfila][e] =75
            elif d[array][subfila][e]== d_mean:
                f[array][subfila][e] =50
            elif d[array][subfila][e]==d_min:
                f[array][subfila][e] =0
            elif d[array][subfila][e]==d_max:
                f[array][subfila][e] =100

f
    




array([[[ 75.,  25.,  25.,  75.,  25.],
        [ 25.,  75.,  75.,  75.,  25.],
        [ 75.,   0.,  75., 100.,  25.]],

       [[ 75.,  75.,  75.,  75.,  25.],
        [ 75.,  25.,  75.,  25.,  75.],
        [ 75.,  25.,  75.,  25.,  25.]]])

In [20]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

print(d)
print(f)




[[[1.98349318 1.39081549 1.39495457 1.66354012 1.35549264]
  [1.3431953  1.8985985  1.98009795 1.73363821 1.46582344]
  [1.79059955 1.08881731 1.95633833 1.99059743 1.38536392]]

 [[1.81124126 1.77190976 1.64098742 1.85584239 1.59998085]
  [1.63480094 1.21124504 1.70146329 1.18897125 1.95623167]
  [1.67646795 1.15407412 1.98190996 1.55392822 1.53395564]]]
[[[ 75.  25.  25.  75.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 75.   0.  75. 100.  25.]]

 [[ 75.  75.  75.  75.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 75.  25.  75.  25.  25.]]]


In [28]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""
g = f.astype(str)
g




array([[['75.0', '25.0', '25.0', '75.0', '25.0'],
        ['25.0', '75.0', '75.0', '75.0', '25.0'],
        ['75.0', '0.0', '75.0', '100.0', '25.0']],

       [['75.0', '75.0', '75.0', '75.0', '25.0'],
        ['75.0', '25.0', '75.0', '25.0', '75.0'],
        ['75.0', '25.0', '75.0', '25.0', '25.0']]], dtype='<U32')

In [32]:

g_new=np.empty((2,3,5))




In [33]:
for array in range(g.shape[0]):
    for subfila in range(g.shape[1]):
        for e in range(g.shape[2]):
            if g[array][subfila][e]=='0.0':
                g_new[array][subfila][e] = "A"
            elif g[array][subfila][e]=='25.0':
                g_new[array][subfila][e] ="B"
            elif g[array][subfila][e]== '50.0':
                g_new[array][subfila][e] ="C"
            elif g[array][subfila][e]=='75.0':
                g_new[array][subfila][e] = "D"
            elif g[array][subfila][e]=='100.0':
                g_new[array][subfila][e] ="E"

g_new

ValueError: could not convert string to float: 'D'