In [1]:
#1. Import the NUMPY package under the name np.

In [2]:
!pip install numpy
import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.

In [4]:
print(np.__version__)

1.20.3


In [5]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
a = np.random.rand(2,3,5)

In [7]:
#4. Print a.

In [8]:
print(a)

[[[0.72285122 0.20139109 0.85135568 0.37762812 0.94057223]
  [0.46347207 0.75517946 0.20127103 0.47797392 0.83279431]
  [0.14866641 0.8011476  0.21871432 0.36441722 0.56143742]]

 [[0.71022133 0.79109951 0.03199877 0.29091776 0.10874405]
  [0.56280431 0.2186726  0.04384614 0.25163432 0.02443872]
  [0.31980048 0.44675614 0.64951731 0.89020033 0.61590608]]]


In [9]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [10]:
b = np.ones((5,2,3))

In [11]:
#6. Print b.

In [12]:
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
#7. Do a and b have the same size? How do you prove that in Python code?

In [14]:
a = np.array (a)
print(np.size(a))

30


In [15]:
b = np.array (b)
print(np.size(b))

30


In [16]:
print(a==b)

False


C:\Users\ORIANA~1\AppData\Local\Temp/ipykernel_14072/1502103540.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(a==b)


In [17]:
#8. Are you able to add a and b? Why or why not?

In [18]:
c = np.add(a, b)  
print(c)  

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
#ERROR: los operandos no se pueden transmitir junto con las formas.

In [ ]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [19]:
c=b.reshape(2,3,5)
print(c)
print(np.shape(c))

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


In [ ]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [20]:
d=a+c
print(d)

[[[1.72285122 1.20139109 1.85135568 1.37762812 1.94057223]
  [1.46347207 1.75517946 1.20127103 1.47797392 1.83279431]
  [1.14866641 1.8011476  1.21871432 1.36441722 1.56143742]]

 [[1.71022133 1.79109951 1.03199877 1.29091776 1.10874405]
  [1.56280431 1.2186726  1.04384614 1.25163432 1.02443872]
  [1.31980048 1.44675614 1.64951731 1.89020033 1.61590608]]]


In [ ]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [21]:
print(a)

[[[0.72285122 0.20139109 0.85135568 0.37762812 0.94057223]
  [0.46347207 0.75517946 0.20127103 0.47797392 0.83279431]
  [0.14866641 0.8011476  0.21871432 0.36441722 0.56143742]]

 [[0.71022133 0.79109951 0.03199877 0.29091776 0.10874405]
  [0.56280431 0.2186726  0.04384614 0.25163432 0.02443872]
  [0.31980048 0.44675614 0.64951731 0.89020033 0.61590608]]]


In [22]:
print(d)

[[[1.72285122 1.20139109 1.85135568 1.37762812 1.94057223]
  [1.46347207 1.75517946 1.20127103 1.47797392 1.83279431]
  [1.14866641 1.8011476  1.21871432 1.36441722 1.56143742]]

 [[1.71022133 1.79109951 1.03199877 1.29091776 1.10874405]
  [1.56280431 1.2186726  1.04384614 1.25163432 1.02443872]
  [1.31980048 1.44675614 1.64951731 1.89020033 1.61590608]]]


In [ ]:
se sumaron los 1 de la matriz b a los valores de la matriz a para crear la nueva matriz

In [ ]:
#12. Multiply a and c. Assign the result to e.

In [23]:
e=np.dot(a,c)

ValueError: shapes (2,3,5) and (2,3,5) not aligned: 5 (dim 2) != 3 (dim 1)

In [ ]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [24]:
d_max=d.max()
d_max

1.9405722338094304

In [25]:
d_min=d.min()
d_min

1.0244387237645434

In [26]:
d_mean=d.mean()
d_mean

1.4625143317833802

In [ ]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [42]:
f = np.empty((2,3,5))
print(f)

[[[1.72285122 1.20139109 1.85135568 1.37762812 1.94057223]
  [1.46347207 1.75517946 1.20127103 1.47797392 1.83279431]
  [1.14866641 1.8011476  1.21871432 1.36441722 1.56143742]]

 [[1.71022133 1.79109951 1.03199877 1.29091776 1.10874405]
  [1.56280431 1.2186726  1.04384614 1.25163432 1.02443872]
  [1.31980048 1.44675614 1.64951731 1.89020033 1.61590608]]]


In [43]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

"""

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d_mean < d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d_min < d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100
                
f


array([[[ 75.,  25.,  75.,  25., 100.],
        [ 75.,  75.,  25.,  75.,  75.],
        [ 25.,  75.,  25.,  25.,  75.]],

       [[ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  25.,  25.,   0.],
        [ 25.,  25.,  75.,  75.,  75.]]])

In [ ]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


In [44]:
print(d)

[[[1.72285122 1.20139109 1.85135568 1.37762812 1.94057223]
  [1.46347207 1.75517946 1.20127103 1.47797392 1.83279431]
  [1.14866641 1.8011476  1.21871432 1.36441722 1.56143742]]

 [[1.71022133 1.79109951 1.03199877 1.29091776 1.10874405]
  [1.56280431 1.2186726  1.04384614 1.25163432 1.02443872]
  [1.31980048 1.44675614 1.64951731 1.89020033 1.61590608]]]


In [45]:
print(f)

[[[ 75.  25.  75.  25. 100.]
  [ 75.  75.  25.  75.  75.]
  [ 25.  75.  25.  25.  75.]]

 [[ 75.  75.  25.  25.  25.]
  [ 75.  25.  25.  25.   0.]
  [ 25.  25.  75.  75.  75.]]]


In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""