In [61]:
#1. Import the NUMPY package under the name np.
#no hace falta el %pip porque ya lo tenía instalado
import numpy as np

#2. Print the NUMPY version and the configuration.

print(np.version.version)

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2, 3, 5))


#4. Print a.
print(a)


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.full((5, 2, 3),1)

#6. Print b.

print(b)

#7. Do a and b have the same size? How do you prove that in Python code?

print(a.shape == b.shape)

#8. Are you able to add a and b? Why or why not?

#No te permite sumar porque no tienen la misma dimensión

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.reshape(b,(2,3,5))


#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d= a+c
print(d)
#it works bc they have equal size

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print('this is a')
print(a)
print('this is b')
print(d)


#12. Multiply a and c. Assign the result to e.
e = a*c
print(f'esto es e')
print(e)


#13. Does e equal to a? Why or why not?

print(a==e) #True

#Porque hemos multiplicado a por c y c son todo 1


#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = d.max()
d_min = d.max()
d_mean = d.mean()
print(f'máximo =', d_max, 'mínimo =', d_min, 'media =', d_mean)

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))
print(f) #Tiene números aleatorios, realmente está vacío


"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""





"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

1.20.3
[[[0.32787609 0.25651382 0.72970288 0.3370269  0.51142787]
  [0.28117138 0.9544047  0.85392506 0.02119961 0.29705391]
  [0.49971465 0.20816328 0.37102685 0.18080285 0.13191604]]

 [[0.39228252 0.73018908 0.06419571 0.75799686 0.33537989]
  [0.63557601 0.44941648 0.66061764 0.78145336 0.37677962]
  [0.13254742 0.07917181 0.17363932 0.75583065 0.04212842]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
False
[[[1.32787609 1.25651382 1.72970288 1.3370269  1.51142787]
  [1.28117138 1.9544047  1.85392506 1.02119961 1.29705391]
  [1.49971465 1.20816328 1.37102685 1.18080285 1.13191604]]

 [[1.39228252 1.73018908 1.06419571 1.75799686 1.33537989]
  [1.63557601 1.44941648 1.66061764 1.78145336 1.37677962]
  [1.13254742 1.07917181 1.17363932 1.75583065 1.04212842]]]
this is a
[[[0.32787609 0.25651382 0.72970288 0.3370269  0.51142787]
  [0.28117138 0.9544047  0.85392506 0.02119961 0.29705391]
  [0.49971465 0.20816328 0.371026

'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'